version: '2'

services:
  etcd1:
    image: bitnami/etcd:3
    container_name: etcd1
    # volumes:
    #   - etcd_data:/bitnami/etcd
    environment:
      - ETCD_NAME=etcd1
      - ALLOW_NONE_AUTHENTICATION=yes
      # Client
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      # Peers
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      # Cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - 2379
      - 2380
    networks:
      etcd_net:

  etcd2:
    image: bitnami/etcd:3
    container_name: etcd2
    # volumes:
    #   - etcd_data:/bitnami/etcd
    environment:
      - ETCD_NAME=etcd2
      - ALLOW_NONE_AUTHENTICATION=yes
      # Client
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      # Peers
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      # Cluster
      - ETCD_INITIAL_CLUSTER=etcd2=http://etcd2:2380,etcd1=http://etcd1:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - 2379
      - 2380
    networks:
      etcd_net:

  etcd3:
    image: bitnami/etcd:3
    container_name: etcd3
    # volumes:
    #   - etcd_data:/bitnami/etcd
    environment:
      - ETCD_NAME=etcd3
      - ALLOW_NONE_AUTHENTICATION=yes
      # Client
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      # Peers
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      # Cluster
      - ETCD_INITIAL_CLUSTER=etcd3=http://etcd3:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - 2379
      - 2380
    networks:
      etcd_net:

  
  e3w:
    image: soyking/e3w:latest
    volumes:
      - ./config.default.ini:/app/conf/config.default.ini
    ports:
      - 8080:8080
    networks:
      etcd_net:
    depends_on:
      - etcd1

# volumes:
#   etcd_data:
#     driver: local

networks:
  etcd_net:
    driver: bridge